export { ICArrowLeft } from './ICArrowLeft'
export { ICArrowDown } from './ICArrowDown'
export { ICPersonCount } from './ICPersonCount'
export { ICStar } from './ICStar'
export { ICTimer } from './ICTimer'
